name: Docker Image CI

on:
  push:
    branches: [ master, ci ]
  repository_dispatch:
    types: [ build ]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: echo "::set-env name=VERSION::$(npm info israeli-bank-scrapers version)"
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: omercnet/israeli-bank-scrapers
        tags: latest, ${{ env.VERSION }}
